import os
import sys
import re
import smtplib
from email.message import EmailMessage

def format_professional_search_report(json_path):
    """Formats the JSON search results into a professional email report."""
    import json
    try:
        with open(json_path, 'r', encoding='utf-8') as f:
            results = json.load(f)
        
        report = "--- 🌐 Professional Search Intelligence Report ---\n\n"
        report += f"Total Results Analyzed: {len(results)}\n"
        report += "-" * 50 + "\n\n"
        
        for idx, res in enumerate(results, start=1):
            report += f"{idx}. {res.get('title', 'Untitled Result').upper()}\n"
            report += f"   🔗 URL: {res.get('url', 'No URL Available')}\n"
            snippet = res.get('snippet', '')
            if snippet:
                report += f"   📝 Summary: {snippet}\n"
            keywords = res.get('keywords', [])
            if keywords:
                report += f"   🏷️ Key Terms: {', '.join(keywords)}\n"
            report += "\n"
            
        report += "-" * 50 + "\n"
        report += "Generated by Croissant Toolkit Communication Officer\n"
        return report
    except Exception as e:
        return f"Warning: Failed to format search report: {e}\n\nRaw Data Follows:\n{json_path}"

def enrich_body_with_search_results(body):
    """Enriches the email body with rich details from google_search_results.json if links are present."""
    import json
    json_path = "google_search_results.json"
    if not os.path.exists(json_path):
        return body

    try:
        with open(json_path, 'r', encoding='utf-8') as f:
            results = json.load(f)
        
        # Build lookup table by URL
        results_map = {res.get('url'): res for res in results}
        
        lines = body.split('\n')
        enriched_lines = []
        
        for line in lines:
            # Check if line looks like a link or list item with link
            # match: 1. http://... or just http://...
            link_match = re.search(r'https?://[^\s,]+', line)
            if link_match:
                url = link_match.group(0).strip('.')
                if url in results_map:
                    res = results_map[url]
                    title = res.get('title', 'Untitled Result').upper()
                    snippet = res.get('snippet', '')
                    
                    # Create a rich block for this link
                    enriched_line = f"🌐 {title}\n"
                    enriched_line += f"   🔗 URL: {url}\n"
                    if snippet:
                        enriched_line += f"   📝 Summary: {snippet}\n"
                    enriched_lines.append(enriched_line)
                    continue
            
            enriched_lines.append(line)
            
        return '\n'.join(enriched_lines)
    except Exception as e:
        print(f"Warning: Enrichment failed: {e}")
        return body

def send_email(recipient, subject, body, attachment_path=None):
    smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USER")
    smtp_pass = os.getenv("SMTP_PASS")

    if not smtp_user or not smtp_pass:
        print("\n[Communication Officer] Error: Email credentials not found.")
        print("Please configure your environment for slava@codata.org:")
        print("export SMTP_USER='slava@codata.org'")
        print("export SMTP_PASS='your-google-app-password'")
        return False

    # Check if body is requesting a professional search report or contains links to enrich
    if body == "google_search_results.json" and os.path.exists(body):
         print("[Communication Officer] Generating professional search report from JSON...")
         body = format_professional_search_report(body)
    else:
         print("[Communication Officer] Enriching email body with metadata...")
         body = enrich_body_with_search_results(body)

    msg = EmailMessage()
    msg.set_content(body)
    msg['Subject'] = subject
    msg['From'] = smtp_user
    msg['To'] = recipient

    if attachment_path and os.path.exists(attachment_path):
        with open(attachment_path, 'rb') as f:
            file_data = f.read()
            file_name = os.path.basename(attachment_path)
            msg.add_attachment(file_data, maintype='application', subtype='octet-stream', filename=file_name)

    try:
        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()
            if smtp_user and smtp_pass:
                server.login(smtp_user, smtp_pass)
            server.send_message(msg)
        print(f"Email successfully sent to {recipient}")
        return True
    except Exception as e:
        print(f"Failed to send email: {e}")
        return False

def main():
    if len(sys.argv) < 4:
        print("Usage: python3 send_email.py <RECIPIENT> <SUBJECT> <BODY_OR_JSON_PATH> [ATTACHMENT_PATH]")
        sys.exit(1)

    recipient = sys.argv[1]
    subject = sys.argv[2]
    body = sys.argv[3]
    attachment = sys.argv[4] if len(sys.argv) > 4 else None

    send_email(recipient, subject, body, attachment)

if __name__ == "__main__":
    main()
